import locale
from datetime import datetime


def gerar_data_extenso():
    """
    Gera a data atual por extenso em português.
    """
    try:
        locale.setlocale(locale.LC_TIME, "pt_BR.utf-8")
    except:
        locale.setlocale(locale.LC_TIME, "Portuguese_Brazil.1252")

    hoje = datetime.now()
    return hoje.strftime("%A, %d de %B de %Y")


evento = {
    "DESCRICAOEVENTO": "EXAGERADO MAIO PAVILHÃO 2026",
    "CPFREPRESENTANTEORGANIZADOR": "013.714.186-67",
    "ENDERECOREPRESENTANTEORGANIZADOR": "Braulina Baptista Lopes, 150, Edíficio, Rosario de Fátima, SERRA/ES. CEP: 29161-121",
    "PERIODOEVENTO": "De 06 de Maio de 2026 à 10 de Maio de 2026",
    "HORARIOEVENTO": "Das 10:00 as 22:00",
    "LOCALEVENTO": "PAVILHÃO DE CARAPINA, SN, PAVILHÃO DE CARAPINA OU PAR. ESTADUAL AGROPECUÁR, CARAPINA, SERRA/ES. CEP: 29161-064.",
    "ANTECEDENCIAENTREGAESPACO": "1",
    "REFERENCIALIBERACAO": "05/05/2026",
    "HORAINICIOLIBERACAO": "09:00",
    "HORATERMINOLIBERACAO": "18:00",
    "PENALIDADEIRREGULARIDADE": "R$ 1.000,00",
    "PENALIDADECONTRATACAOMENOR": "R$ 1.000,00",
    "PENALIDADERESCISAO": "R$ 1.000,00",
    "EXPOSITORDATALIMITEPAGAMENTO": "31/03/2026",
    "PRAZOENVIOLOGOMARCA": "04/05/2026",
    "PENALIDADEMARCA": "R$ 1.000,00",
    "PENALIDADEDESVIOFINALIDADE": "R$ 1.000,00",
    "PORCENTEGEMLIMITEESTOQUEMINIMO": "20%",
    "PORCENTAGEMINFRACAOLIMITEESTOQUEMINIMO": "30%",
    "PENALIDADEDANOSMINIMOS": "R$ 50,00",
    "PENALIDADEDANOSMAXIMOS": "R$ 5.000,00",
    "PENALIDADESUBLOCACAO": "R$ 5.000,00",
    "INFRACAODESCONTO": "R$ 1.000,00",
    "VALECOMPRA": "R$ 100,00",
    "PRAZOMAXIMOOCUPACAOESPACO": "8 horas",
    "PENALIDADEQUEBRACONTRATO": "R$ 2.000,00",
    "HORARIOEXPOSITOR": "09:30 horas",
    "PENALIDADEATRASOABERTURA": "R$ 100,00",
    "HORARIOABERTURA2": "10:00 horas",
    "HORARIOFECHAMENTO": "22:00 horas",
    "TOLERANCIAFECHAMENTO": "30 minutos",
    "MULTAATRASOFECHAMENTO": "R$ 100,00",
    "HORARIOLIMITEFECHAMENTO": "22:30",
    "DATAPAGAMENTOALUGALSTAND": "04/05/2026",
    "DATAENTRADA": "20/03/2025",
    "DATAEXTENSO": gerar_data_extenso(),
}